title:              SenWei's Blog
email:              abc@xyz.com
description:        My Blog
author:             Senwei Liang
baseurl:            ""
url:                ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
